---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - ln -s ansible-role-s3fs ../Aplyca.S3fs

install:
  # Install Ansible.
  - sudo pip install -r tests/requirements.txt

script:
  - tests/tests.sh

notifications:
  email: false
